/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/users': {
		/** @description Get users */
		get: {
			responses: {
				/** @description OK */
				200: {
					content: {
						'application/json': components['schemas']['User'][]
					}
				}
				/** @description Unexpected error */
				default: {
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
	}
}

export type webhooks = Record<string, never>

export interface components {
	schemas: {
		Error: {
			message: string
			stack?: string
			axiosError?: string
		}
		User: {
			name?: string
		}
	}
	responses: {
		/** @description Unauthorized */
		Unauthorized: {
			content: {
				'application/json': components['schemas']['Error']
			}
		}
	}
	parameters: never
	requestBodies: never
	headers: never
	pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export type operations = Record<string, never>
